name: Check Flight Price with Puppeteer

on:
  schedule:
    - cron: '*/15 * * * *'  # 每15分鐘跑一次
  workflow_dispatch:

jobs:
  run-check:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install puppeteer node-fetch

      - name: Run Puppeteer script
        env:
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
        run: node check_price2.mjs

      - name: Upload artifacts
        if: always()  # 無論成功或失敗都上傳
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: |
            artifacts/error_screenshot.png
            artifacts/error_page.html
          retention-days: 7  # 保留 7 天，可根據需要調整